### ISSUE TITLE
Is is possible to extract imported functions?

### ISSUE THREAD

**Issue by adinapoli** [finnsson/template-helper#6]
Hi there,

I'm using your interesting library. Is this possible?

```
import Foo
$(functionExtractor "regexMatchingSomethingInFoo")
```

in other terms, is it possible to extract functions from imported modules?

Thanks!
A.

**Comment by finnsson** [comment]
Hi,

I'm afraid that's not possible. The function `functionExtractor` will simply inspect the source code of the current file and extract methods with matching names.

**Comment by adinapoli** [comment]
I suspected that. Thanks anyway :)
